name: Build and publish

on:
  push:
    branches:  
      - master
      - main
      - release/**

jobs:
  build-and-test:
    uses: SKProCH/CommonWorkflows/.github/workflows/build-publish.yml@main
    secrets:
      NUGET_KEY: ${{ secrets.NUGET_KEY }}
    with:
      publish-nightly: false
      dotnet-version: 8